$(EmulatorDir): ""
/dev_hdd0/: V:/RetroBat/roms/ps3/virtualFS/dev_hdd0/
/dev_hdd1/: V:/RetroBat/roms/ps3/virtualFS/dev_hdd1/
/dev_flash/: V:/RetroBat/roms/ps3/virtualFS/dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_usb000/: V:/RetroBat/roms/ps3/virtualFS/dev_usb000/
/dev_bdvd/: ""
/app_home/: ""